const projects = [
  {
    id: 1,
    label: 'Countries infos',
    name: 'countries-info',
    description: 'Um site para visualizar informações de países do mundo',
    site: 'https://countries-infos.onrender.com/',
    github: 'https://github.com/Josimar-Souza/countries-info',
    imagePath: '../../images/projects/countries-infos.png',
  },
  {
    id: 2,
    label: 'Sharp Movies',
    name: 'sharp-movies',
    description: 'Um site para visualizar filmes e séries',
    site: 'https://sharp-movies.onrender.com/movies',
    github: 'https://github.com/Josimar-Souza/movies-site',
    imagePath: '../../images/projects/sharp-movies.png',
  },
  {
    id: 3,
    label: 'Games library API',
    name: 'games-library-api',
    description: 'API para alimentar uma biblioteca de jogos pessoal!',
    site: null,
    github: 'https://github.com/Josimar-Souza/games-library-backend',
    imagePath: '../../images/projects/games-library-api.png',
  },
  {
    id: 4,
    label: 'Temperature converter',
    name: 'temperature-converter',
    description: 'Uma simples site para converter temperatura celsius para fahrenheit',
    site: 'https://temperature-converter-wjri.onrender.com/',
    github: 'https://github.com/Josimar-Souza/Temperature-converter',
    imagePath: '../../images/projects/temperature-converter.png',
  },
  {
    id: 5,
    label: 'Calculadora',
    name: 'calculator',
    description: 'Uma simples calculadora',
    site: 'https://calculator-8e08.onrender.com/',
    github: 'https://github.com/Josimar-Souza/Calculator',
    imagePath: '../../images/projects/calculator.png',
  },
  {
    id: 6,
    label: 'Music Library',
    name: 'music-library',
    description: 'Um simples site com o layout de uma biblioteca de músicas',
    site: 'https://music-library-rvct.onrender.com/',
    github: 'https://github.com/Josimar-Souza/devchallenge-music-library-page',
    imagePath: '../../images/projects/music-library.png',
  },
];

export default projects;
